other_data = {
    "Data": [
        {
            "MGroupCode": "DAD05BR206",
            "ProdName": "【長榮峴在GO】峴港５日-贈魅力秀、法城巴拿山、迦南島桶船、夜遊會安DIY、美溪沙灘",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 24700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00097253.JPG"
        },
        {
            "MGroupCode": "DAD05BR214",
            "ProdName": "【長榮-峴在出發】峴港５日-全程五星飯店、順化古城、法式巴拿山、迦南島桶船、海鮮蒸籠宴、痛風鍋龍蝦餐、特色印度支那餐",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 32700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001847/00094875.JPG"
        },
        {
            "MGroupCode": "DAD05BR333",
            "ProdName": "【長榮峴在GO】峴港５日-升等兩晚五星飯店、贈魅力秀、法城巴拿山、迦南島桶船、夜遊會安DIY、美溪沙灘",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 44100,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00055255.jpg"
        },
        {
            "MGroupCode": "DAD05CI209",
            "ProdName": "【花峴中越】峴港５日-贈魅力峴港秀、法式巴拿山、迦南島桶船、會安古鎮燈籠手作、美溪沙灘、龍蝦海鮮餐",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 25900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00035468.JPG"
        },
        {
            "MGroupCode": "DAD05CI444",
            "ProdName": "【花峴中越】峴港５日-升等兩晚五星飯店、贈魅力峴港秀、法式巴拿山、迦南島桶船、會安古鎮燈籠手作、美溪沙灘、龍蝦海鮮餐",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 50700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00055255.jpg"
        },
        {
            "MGroupCode": "DAD05IT23-01",
            "ProdName": "【超值在峴】峴港5日~迦南島.會安古鎮.巴拿山(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 19388,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": ""
        },
        {
            "MGroupCode": "DAD05ITK001",
            "ProdName": "繽紛再峴~峴港.會安古鎮.會安印象秀.迦南島.巴拿山.美山遺址5日",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 33000,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084265.jpg"
        },
        {
            "MGroupCode": "DAD05ITK003",
            "ProdName": "神氣活峴~峴港.會安古鎮.魅力峴港秀.迦南島.巴拿山.美山遺址5日",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 27500,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00055256.jpg"
        },
        {
            "MGroupCode": "DAD05ITK009",
            "ProdName": "【升級版】惠選峴港~迦南島.會安古鎮.巴拿山.五行山.美山聖地五日",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 22999,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00068765.jpg"
        },
        {
            "MGroupCode": "DAD05ITT201",
            "ProdName": "【飛虎上峴】峴港５日-會安古鎮、粉紅教堂、山茶半島、龍蝦海鮮餐",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 21900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00055255.jpg"
        },
        {
            "MGroupCode": "DAD05JX1104",
            "ProdName": "Chill秋優惠【星宇】峴港５日-升等五星飯店、贈越式洗頭",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 26300,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084263.jpg"
        },
        {
            "MGroupCode": "DAD05JX1218",
            "ProdName": "Chill優惠【星宇午班機】峴港５日-五星一晚、贈越式洗頭",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 26700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00097257.JPG"
        },
        {
            "MGroupCode": "DAD05JX202",
            "ProdName": "【峴定星宇.早班機】峴港５日-法式巴拿山、迦南島桶船、船遊會安古鎮、龍蝦海鮮餐、椰子果凍、越共咖啡",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 25700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084263.jpg"
        },
        {
            "MGroupCode": "DAD05JX211",
            "ProdName": "【星尊寵】峴港５日-贈SPA按摩、全程五星飯店、巴拿山+法國酒窖、船遊韓江、層層塔海鮮餐、海鮮痛風鍋+龍蝦、燒烤吃到飽",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 31900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/002525/002526/00073317.jpg"
        },
        {
            "MGroupCode": "DAD05JX217",
            "ProdName": "【峴定星宇.午班機】峴港５日-法式巴拿山、迦南島桶船、會安古鎮燈籠手作、粉紅教堂、美溪沙灘、龍蝦海鮮餐",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 26100,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084263.jpg"
        },
        {
            "MGroupCode": "DAD05JX444",
            "ProdName": "【峴定星宇.午班機】峴港５日-升等兩晚五星飯店、法式巴拿山、迦南島桶船、會安古鎮燈籠手作、粉紅教堂、美溪沙灘、龍蝦海鮮餐",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 34900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00055255.jpg"
        },
        {
            "MGroupCode": "DAD05QH23-2",
            "ProdName": "竹夢在峴5日～迦南島.會安古鎮.巴拿山(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 26500,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084266.jpg"
        },
        {
            "MGroupCode": "DAD05QH23-3",
            "ProdName": "峴港好好玩5日～迦南島.會安古鎮.巴拿山(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 22599,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084263.jpg"
        },
        {
            "MGroupCode": "DAD05QH23-4",
            "ProdName": "璀璨在峴5日～迦南島.會安古鎮.巴拿山(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 31800,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084265.jpg"
        },
        {
            "MGroupCode": "DAD05QH23-6",
            "ProdName": "【超值在峴】峴港5日~迦南島.會安古鎮.巴拿山(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 19388,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": ""
        },
        {
            "MGroupCode": "DAD05VJ23-2",
            "ProdName": "竹夢在峴5日(VJ)～迦南島.會安古鎮.巴拿山(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 26500,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084266.jpg"
        },
        {
            "MGroupCode": "DAD05VJ23-3",
            "ProdName": "峴港好好玩5日(VJ)～迦南島.會安古鎮.巴拿山(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 22599,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084263.jpg"
        },
        {
            "MGroupCode": "DAD05VJ23-4",
            "ProdName": "璀璨在峴5日(VJ)～迦南島.會安古鎮.巴拿山(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 31800,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084265.jpg"
        },
        {
            "MGroupCode": "DAD06IT23-01",
            "ProdName": "【超值在峴】峴港+順化6日~迦南島.會安古鎮.巴拿山(無購物",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 21888,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": ""
        },
        {
            "MGroupCode": "DAD06ITK001",
            "ProdName": "繽紛再峴~峴港.會安古鎮.迦南島.巴拿山.印象會安秀.美山遺址.順化皇城6日",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 35800,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084265.jpg"
        },
        {
            "MGroupCode": "DAD06ITK002",
            "ProdName": "神氣活峴~峴港.會安古鎮.魅力峴港秀.迦南島.巴拿山.美山遺址.順化皇城6日",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 30500,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00055256.jpg"
        },
        {
            "MGroupCode": "DAD06ITK006",
            "ProdName": "【升級版】惠選峴港~迦南島.會安古鎮.巴拿山.山茶半島.順化六日",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 24999,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00068765.jpg"
        },
        {
            "MGroupCode": "DAD06QH23-2",
            "ProdName": "竹夢在峴6日(無購物)越竹航空-會安古鎮.順化古城.巴拿山.魅力峴港秀",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 28800,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001847/00094875.JPG"
        },
        {
            "MGroupCode": "DAD06QH23-3",
            "ProdName": "峴港好好玩6日(無購物)越竹航空-順化三輪車.魅力峴港秀",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 24999,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00082700.jpg"
        },
        {
            "MGroupCode": "DAD06QH23-4",
            "ProdName": "璀璨在峴6日～迦南島.會安古鎮.巴拿山.啟定皇陵(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 34800,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00073423.jpg"
        },
        {
            "MGroupCode": "DAD06QH23-6",
            "ProdName": "【超值在峴】峴港+順化6日~迦南島.會安古鎮.巴拿山(無購物",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 21888,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": ""
        },
        {
            "MGroupCode": "DAD06VJ23-2",
            "ProdName": "竹夢在峴6日(VJ)~會安古鎮.順化古城.巴拿山.魅力峴港秀(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 28800,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001847/00094875.JPG"
        },
        {
            "MGroupCode": "DAD06VJ23-3",
            "ProdName": "峴港好好玩6日(VJ)-越竹航空-順化三輪車.魅力峴港秀(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 24999,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00082700.jpg"
        },
        {
            "MGroupCode": "DAD06VJ23-4",
            "ProdName": "璀璨在峴6日(VJ)～迦南島.會安古鎮.巴拿山.啟定皇陵(無購物)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 34800,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(中越峴港.會安.順化)",
            "TravelNationName": "越南",
            "TravelCityName": "峴港",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00073423.jpg"
        },
        {
            "MGroupCode": "HAN05BR0033",
            "ProdName": "Chill優惠【長榮】河內５日-國賓2號遊船",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 20500,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00097103.jpg"
        },
        {
            "MGroupCode": "HAN05BR202",
            "ProdName": "【天堂雅儷】越南河內５日-全程五星飯店、海上VILLA、雙龍灣、水上木偶戲",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 35100,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00035392.JPG"
        },
        {
            "MGroupCode": "HAN05BR208",
            "ProdName": "【長榮飛越】越南河內５日－船遊下龍灣、纜車摩天輪、水上木偶戲、寧平陸龍灣",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 22700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/002480/002487/00060746.jpg"
        },
        {
            "MGroupCode": "HAN05BR555",
            "ProdName": "長榮.早班機【賓賓有你】河內５日－海鮮自助餐、國賓2號日遊船、下龍灣、陸龍灣、纜車摩天輪",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 25900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00095701.JPG"
        },
        {
            "MGroupCode": "HAN05CI209",
            "ProdName": "華航【越越欲趣】北越河內５日-國賓二號日遊船、雙龍灣、纜車摩天輪、蓮花自助餐",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 30900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00095711.PNG"
        },
        {
            "MGroupCode": "HAN05CI211",
            "ProdName": "【越南小瑞士】河內５日－國賓號遊船、三島仙境、石頭教堂、下龍灣、陸龍灣、維納斯城堡飯店",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 30900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/002480/002936/00096259.JPG"
        },
        {
            "MGroupCode": "HAN05CI444",
            "ProdName": "華航.早班機【賓賓有你】河內５日－海鮮自助餐、國賓2號日遊船、下龍灣、陸龍灣、纜車摩天輪",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 43700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00095701.JPG"
        },
        {
            "MGroupCode": "HAN05JX1101",
            "ProdName": "旅展一口價Chill優惠【星宇】河內５日-國賓2號遊船",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 21900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00097103.jpg"
        },
        {
            "MGroupCode": "HAN05JX444",
            "ProdName": "星宇.早班機【賓賓有你】河內５日－海鮮自助餐、國賓2號日遊船、下龍灣、陸龍灣、纜車摩天輪",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 43700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00095701.JPG"
        },
        {
            "MGroupCode": "HAN05VN007",
            "ProdName": "愛戀海上villa北越雙龍灣5日-國賓一號.皇后雙層纜車",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 35800,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/000026/000353/00005306.JPG"
        },
        {
            "MGroupCode": "HAN05VN23-1",
            "ProdName": "輕鬆玩北越雙龍五日-下龍灣VIP日遊船.陸龍灣.雙層纜車(越捷)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 21500,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": ""
        },
        {
            "MGroupCode": "HAN09VN004",
            "ProdName": "北中南越南全覽９日(北進南出)-北越雙龍灣、會安古鎮、順化皇城、瘋狂竹筒船、古芝地道、西貢河遊船",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 39700,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內/峴港/胡志明市(西貢)",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084270.jpg"
        },
        {
            "MGroupCode": "HANK05VJ0117",
            "ProdName": "浪漫日遊國賓號北越５日-國賓二號.雙龍灣.纜車+摩天輪(VJ)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 24500,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00095701.JPG"
        },
        {
            "MGroupCode": "HANK05VN0117",
            "ProdName": "浪漫日遊國賓號北越５日-國賓二號.雙龍灣.纜車+摩天輪(VN)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 30900,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00095701.JPG"
        },
        {
            "MGroupCode": "HANK05VN017",
            "ProdName": "愛戀海上VILLA天堂雅儷號~北越雙龍灣5日遊~無購物",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 35900,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(北越河內.下龍灣)",
            "TravelNationName": "越南",
            "TravelCityName": "河內",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00095943.JPG"
        },
        {
            "MGroupCode": "PQC05JX007",
            "ProdName": "【★直飛.免簽證】越南富國島５日-五星飯店、南島出海、珍珠奇幻樂園、夜遊大世界、全景跨海纜車、異形沙灘下午茶",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 44900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(胡志明.芽莊.富國島)",
            "TravelNationName": "越南",
            "TravelCityName": "富國島",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00097223.JPG"
        },
        {
            "MGroupCode": "PQC05JX008",
            "ProdName": "越富有【★直飛.免簽證】越南富國島５日-五星飯店、珍珠奇幻樂園、夜遊大世界、香島水上樂園+跨海纜車",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 42900,
            "DeptPlaceName": "台北-桃園機場",
            "Discount": "",
            "SubTravelAreaName": "越南(胡志明.芽莊.富國島)",
            "TravelNationName": "越南",
            "TravelCityName": "富國島",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00097309.JPG"
        },
        {
            "MGroupCode": "PQC05K0001",
            "ProdName": "【島國之戀】富國島貝殼SPA渡假村自由行5天(含稅含早餐贈接送機)",
            "ProdType": "1",
            "RegionType": "O",
            "AreaName": "中南半島KH",
            "MinPrice": 23299,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "中南半島",
            "TravelNationName": "越南",
            "TravelCityName": "富國島",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084284.jpg"
        },
        {
            "MGroupCode": "PQC05K0002",
            "ProdName": "【島國之戀】富國島SONAGA HOTEL自由行5天(含早贈接送機)",
            "ProdType": "1",
            "RegionType": "O",
            "AreaName": "中南半島KH",
            "MinPrice": 19699,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "中南半島",
            "TravelNationName": "越南",
            "TravelCityName": "富國島",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084284.jpg"
        },
        {
            "MGroupCode": "PQC05VN23-1",
            "ProdName": "【漫遊富國島】～胡志明閒情趣、珍珠雙樂園、跳島海景纜車5日(購物一站)",
            "ProdType": "0",
            "RegionType": "O",
            "AreaName": "中南半島",
            "MinPrice": 33900,
            "DeptPlaceName": "高雄-小港機場",
            "Discount": "",
            "SubTravelAreaName": "越南(胡志明.芽莊.富國島)",
            "TravelNationName": "越南",
            "TravelCityName": "富國島",
            "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00096932.JPG"
        }
    ],
    "TokenExpires": "0001-01-01T00:00:00",
    "rCode": "0001",
    "rCodeDesc": "Success"
}



class moko_database {
    constructor(data) {
        this.data = data;
    }

}
// "MGroupCode": "DAD05JX1104",
// "ProdName": "Chill秋優惠【星宇】峴港５日-升等五星飯店、贈越式洗頭",
// "ProdType": "0",
// "RegionType": "O",
// "AreaName": "中南半島",
// "MinPrice": 26300,
// "DeptPlaceName": "台北-桃園機場",
// "Discount": "",
// "SubTravelAreaName": "越南(中越峴港.會安.順化)",
// "TravelNationName": "越南",
// "TravelCityName": "峴港",
// "ImgUrl": "/eWeb_lifetour/IMGDB/001393/001395/00084263.jpg"

// const set_data_Btn = window.document.getElementById('set_data');

// set_data_Btn.addEventListener("click", function () {
//     console.log(other_data.Data.length);
//     const data_table_table = window.document.getElementById('data_table');

//     for (index = 0; index < other_data.Data.length; index++) {
//         var row = data_table_table.insertRow(-1);// 從最後一行新增一列(row)
//         // 新增每列(row)中的元素(cell)

//         row.insertCell(0).innerHTML = other_data.Data[index].AreaName;

//         row.insertCell(1).innerHTML = other_data.Data[index].MinPrice;

//         row.insertCell(2).innerHTML = other_data.Data[index].ProdName;

//     }
// });

